lib/sapients_web/router.ex
defmodule SapientsWeb.Router do
  use SapientsWeb, :router

  import SapientsWeb.UserAuth
  import SapientsWeb.PageController

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SapientsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :pick_palette
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SapientsWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/sapient/:username", PageController, :show
    get "/contact", ContactController, :index
    get "/about", AboutController, :index
    get "/.well-known/nostr.json", NostrController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SapientsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SapientsWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes
  scope "/admin", SapientsWeb do
    pipe_through [:browser, :require_authenticated_admin]

    live "/", AdminLive
    resources "/invite_tokens", TokenController
    resources "/names", NIP05Controller
  end

  scope "/", SapientsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SapientsWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SapientsWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  scope "/profile", SapientsWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/", ProfileController, :index
    resources "/posts", PostController
    resources "/links", LinkController

    live "/sd", SdLive.Index

    live "/images", ImageLive.Index, :index
    live "/images/new", ImageLive.Index, :new
    live "/images/:id/edit", ImageLive.Index, :edit

    live "/panoramas", PanoramaLive.Index, :index
    live "/panoramas/new", PanoramaLive.Index, :new
    live "/panoramas/:id/edit", PanoramaLive.Index, :edit
  end
end

lib/sapients_web/controllers/profile_controller.ex
defmodule SapientsWeb.ProfileController do
  use SapientsWeb, :controller

  alias Sapients.Media

  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end

  def index(conn, _params, current_user) do
    links = Media.list_user_links(current_user)
    posts = Media.list_user_posts(current_user)
    render(conn, "index.html", links: links, posts: posts)
  end
end

lib/sapients_web/views/profile_view.ex
defmodule SapientsWeb.ProfileView do
  use SapientsWeb, :view
end

lib/sapients_web/templates/profile/index.html.heex
<div class="space-y-10">
    <h1 class="text-3xl font-medium">Profile page: <span class="font-thin"><%= @current_user.email %></span></h1>

    <%= link "Your uploaded images", to: Routes.image_index_path(@conn, :index), class: "text-xl link" %>
    <br>
    <%= link "Your panoramas", to: Routes.panorama_index_path(@conn, :index), class: "text-xl link" %>

    <div>
        <h2 class="text-4xl font-bold">Social media links</h2>

        <span class="link"><%= link "New Link", to: Routes.link_path(@conn, :new) %></span>

        <div class="mt-5 flex flex-col gap-7">
            <%= for link <- @links do %>
                <div class="flex items-center justify-between border-2 border-blue-clue">
                    <%= link link.url, to: link.url, class: "p-5" %>

                    <div class="p-5 border-l-2 border-blue-clue flex gap-5">
                        <span><%= link "Show", to: Routes.link_path(@conn, :show, link), class: "link" %></span>
                        <span><%= link "Edit", to: Routes.link_path(@conn, :edit, link), class: "link" %></span>
                        <span><%= link "Delete", to: Routes.link_path(@conn, :delete, link), class: "link", method: :delete, data: [confirm: "Are you sure?"] %></span>
                    </div>
                </div>
            <% end %>
        </div>
    </div>

    <div>
        <h1 class="text-4xl font-bold">Listing Posts</h1>

        <span class="link"><%= link "New Post", to: Routes.post_path(@conn, :new) %></span>

        <div class="mt-5 flex flex-col gap-7">
            <%= for post <- @posts do %>
                <div class="flex items-center justify-between border-2 border-blue-clue">
                    <div class="flex gap-5">
                        <img src={post.image} class="h-20 aspect-video object-cover">
                        <p><%= post.title %></p>
                    </div>

                    <div class="p-5 h-20 border-l-2 border-blue-clue flex items-center gap-5">
                        <span><%= link "Show", to: Routes.post_path(@conn, :show, post), class: "link" %></span>
                        <span><%= link "Edit", to: Routes.post_path(@conn, :edit, post), class: "link" %></span>
                        <span><%= link "Delete", to: Routes.post_path(@conn, :delete, post), class: "link", method: :delete, data: [confirm: "Are you sure?"] %></span>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>